#28 Implemented CRUD methods for payment_transaction table
Sem4enko/asd-java-intern pull request #30
Opened 2022-11-03 15:26 UTC by Sem4enko

2022-11-04 09:18 UTC, vasylnikorych commented on src/main/java/team/asd/dao/PaymentTransactionDao.java
> +	PaymentTransaction update(Integer id);
on create and update should be transferred PaymentTransaction object instead id

2022-11-04 09:18 UTC, vasylnikorych commented on src/main/java/team/asd/entity/PaymentTransaction.java
> +	private Date version;
change to camelCase style

2022-11-07 10:14 UTC, rdovgan requested changes

2022-11-07 10:14 UTC, rdovgan commented on src/main/java/team/asd/constant/PaymentTransactionFundsHolder.java
> +public enum PaymentTransactionFundsHolder {
please change enum name to `FundsHolderEnum` because it will be used for other purposes

2022-11-07 10:14 UTC, rdovgan commented on src/main/java/team/asd/service/PaymentTransactionService.java
> +		return null;
No need to create a PR with empty implementation

2022-11-10 17:10 UTC, rdovgan commented on src/main/java/team/asd/service/PaymentTransactionService.java
> +		checkPaymentTransaction(paymentTransaction);
On update, only `id` field is required

2022-11-11 08:32 UTC, rdovgan commented on src/test/java/team/asd/service/PaymentTransactionServiceTest.java
> +	public void initParty() {
👏

2022-11-11 14:44 UTC, rdovgan approved these changes

2022-11-11 16:27 UTC, merged